sudo: required
services:
  - docker

before_install:
  - docker build -t mukesh51/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mukesh51/react-test npm test -- --coverage

after_success:
  - docker build -t mukesh51/multi-client ./client
  - docker build -t mukesh51/multi-nginx ./nginx
  - docker build -t mukesh51/multi-server ./server
  - docker build -t mukesh51/multi-worker ./worker
  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take above images and push it to Docker Hub
  - docker push mukesh51/multi-client
  - docker push mukesh51/multi-nginx
  - docker push mukesh51/multi-server
  - docker push mukesh51/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-220144007306
  bucket_path: multi-docker 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY    
